### ISSUE TITLE
provide the pretrained model

### ISSUE THREAD

**Issue by sara713** [gabrieltseng/solar-panel-segmentation#11]
hi
would u please provide the pretrained model for testing?
the data is too huge. all people can't work with it.
if u would only put the necessary files and weights of the pretrained model, it will be so beneficial.
tnx in advance

**Comment by gabrieltseng** [comment]
Hi! Unfortunately, I trained these models a number of years ago, so I no longer have the model checkpoints. I have also since fixed a [bug](https://github.com/gabrieltseng/solar-panel-segmentation/commit/a76afc0de44fafda041e680776d042d07ae57046) without retraining the models, which means those models would not work with the updated code.

If you are constrained for compute or storage, most cloud compute providers offer free startup credit (e.g. google provides [$300 in credits on signup](https://cloud.google.com/free)) which should be sufficient to train these models and to manage the data.

**Comment by sara713** [comment]
tnx for immediate response.
